M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-03-08T12:20:45-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-08T12:20:45-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X110.5Y-110.0
X110.5Y-144.5
X156.0Y-110.0
X156.0Y-144.5
M30
